apiVersion: notifik.freepik.com/v1alpha1
kind: Notification
metadata:
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/instance: notification-sample-alertmanager-yaml
    app.kubernetes.io/part-of: notifik
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: notifik
  name: notification-sample-alertmanager-yaml
spec:
  # Resource to be watched
  watch:
    group: ""
    version: v1
    resource: configmaps

    # (Optional) It's possible to watch specific resources
    # name: testing
    # namespace: default

  conditions:
    - name: check-configmap-name
      # The 'key' field admits vitamin Golang templating (well known from Helm)
      # The result of this field will be compared with 'value' for equality
      key: |
        {{- $source := .object -}}
        {{- printf "%s" $source.metadata.name -}}
      value: testing

  message:
    reason: "NameMatchedAlert"
    data: |
      {{- $source := .object -}}
      {{- $now := (now | date "2006-01-02T15:04:05Z07:00") -}}
      {{- $alertStructure := (printf `
        startsAt: "%s"
        annotations:
          additionalProp1: string
          additionalProp2: string
        labels:
          namespace: %s
          name: %s
        generatorURL: string-placeholder` $now $source.metadata.namespace $source.metadata.name) -}}
      {{- fromYaml $alertStructure | toJson -}}
